### ISSUE TITLE
replace _ with cdp_ for field prefixes

### ISSUE THREAD

**Issue by sergehuber** [sergehuber/cdp-graphql-api#42]

**Comment by sergehuber** [comment]
Ok, I have done the change, so for example : 

_sourceID
becomes
cdp_sourceID

I hope that's acceptable, otherwise, we could also do cdp_SourceID but that is a little more involved since simple search/replaces won't work.

**Comment by sigdestad** [comment]
I think you dont need capitol letters when separating with _, so this is fine by me!

**Comment by sergehuber** [comment]
Ok thanks for your quick feedback, I'll close this issue then.
